# Generated by Django 5.2 on 2025-07-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('review_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('content', models.TextField()),
                ('thumbs_up', models.PositiveIntegerField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apps.app')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AppStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('min_installs', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('ratings', models.PositiveIntegerField()),
                ('reviews', models.PositiveIntegerField()),
                ('updated', models.DateField()),
                ('version', models.CharField(max_length=50)),
                ('ad_supported', models.BooleanField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='apps.app')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('app', 'timestamp')},
            },
        ),
    ]
