# Generated by Django 5.2 on 2025-07-21 14:27
# your_app_name/migrations/0002_add_predefined_apps.py

from django.db import migrations


def add_apps(apps, schema_editor):
    App = apps.get_model("apps", "App")

    predefined_apps = [
        ("org.telegram.messenger", "Messaging"),
        ("com.whatsapp", "Messaging"),
        ("ir.mci.ecareapp", "Operators"),
        ("com.myirancell", "Operators"),
        # ("com.rightel.app", "Operators"),
        ("com.bpm.sekeh", "Finance"),
        # ("com.sevenfoourseven724", "Finance"),
        ("ir.tgbs.peccharge", "Finance"),
        ("com.shatelland.namava.mobile", "Video"),
        # ("com.telewebion", "Video"),
        ("ir.tamashakhonehtv", "Video"),
        ("com.plus9.fandogh", "Word Games"),
        ("com.BrainLadder.AmirzaGP", "Word Games"),
        ("picturewordgame.wordpuzzle.crosswordsearch", "Word Games"),
        ("com.instagram.android", "Social"),
        ("com.facebook.katana", "Social"),
        ("com.zhiliaoapp.musically", "Social"),
    ]

    for package_name, category in predefined_apps:
        App.objects.get_or_create(
            package_name=package_name, defaults={"category": category}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),  # or whatever your initial migration is
    ]

    operations = [
        migrations.RunPython(add_apps),
    ]
