# Generated by Django 5.2 on 2025-07-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_add_predefined_apps'),
        ('apps', '0011_add_predefined_apps'),
    ]

    operations = [
    ]
