# Generated by Django 5.2.4 on 2025-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_appreview_appstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstat',
            name='min_installs',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='appstat',
            name='reviews',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='appstat',
            name='updated',
            field=models.BigIntegerField(),
        ),
    ]
