stages:
  - setup
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk add --no-cache bash
  - chmod +x docker/run.sh

setup:
  stage: setup
  script:
    - ./docker/run.sh

test:
  stage: test
  script:
    - ./docker/run.sh
    - docker compose exec api python manage.py test

deploy:
  stage: deploy
  script:
    - ./docker/run.sh
    - docker compose exec kafka kafka-topics.sh --create --topic app_stats --partitions 1 --replication-factor 1 --bootstrap-server localhost:9092 || true
    - docker compose exec kafka kafka-topics.sh --create --topic app_reviews --partitions 1 --replication-factor 1 --bootstrap-server localhost:9092 || true
    - docker compose exec kafka kafka-topics.sh --alter --topic app_stats --partitions 3 --bootstrap-server localhost:9092
    - docker compose exec kafka kafka-topics.sh --alter --topic app_reviews --partitions 3 --bootstrap-server localhost:9092
    - docker compose up -d --scale consumer=3