version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sahab
      POSTGRES_USER: sahab
      POSTGRES_PASSWORD: sahab
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sahab"]
      interval: 3s
      timeout: 3s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    command: >
          sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../api:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy



    

  crawler:
    build:
      context: ..
      dockerfile: crawler/Dockerfile
    command: python main.py
    volumes:
      - ../crawler:/app
    depends_on:
      - api
      - kafka
    restart: on-failure
  

  consumer:
    build:
      context: ..
      dockerfile: consumer/Dockerfile
    command: python main.py
    volumes:
      - ../consumer:/app
    depends_on:
      - db
      - kafka

  # airflow:
  #   image: apache/airflow:2.7.0
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://sahab:sahab@db:5432/sahab
  #     AIRFLOW__CORE__FERNET_KEY: your_fernet_key_here
  #     AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags

volumes:
  db_data: