name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make `run.sh` Executable
        run: chmod +x docker/run.sh

      - name: Start Services
        run: ./docker/run.sh

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make `run.sh` Executable
        run: chmod +x docker/run.sh

      - name: Run Tests
        run: ./docker/run.sh

  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    needs: test
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make `run.sh` Executable
        run: chmod +x docker/run.sh

      - name: Deploy Services
        run: ./docker/run.sh