name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Services
        run: |
          docker compose down
          docker compose up -d

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Django Tests
        run: |
          docker compose exec api python manage.py test

  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    needs: test
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy Services
        run: |
            docker compose down
            docker compose up -d